export const columns = [
  {
    name: "product_code",
    align: "left",
    label: "Código",
    field: "product_code",
    type: "text",
    sortable: true,
  },
  {
    name: "product_category",
    align: "left",
    label: "Categoria",
    field: "product_category",
    type: "text",
    sortable: true,
  },
  {
    name: "product_name",
    align: "left",
    label: "Nome",
    field: "product_name",
    type: "text",
    sortable: true,
  },
  {
    name: "OS",
    align: "left",
    label: "OS",
    field: "OS",
    type: "info",
    sortable: true,
  },
  {
    name: "requested_quantity",
    align: "right",
    label: "Solicitado",
    field: "requested_quantity",
    type: "number",
    sortable: true,
  },
  {
    name: "invoiced_quantity",
    align: "right",
    label: "Confirmado",
    field: "invoiced_quantity",
    type: "number",
    sortable: true,
  },
  {
    name: "product_cost",
    align: "right",
    label: "Custo Unitário",
    field: "product_cost",
    type: "currency",
    sortable: true,
  },
  {
    name: "total_cost",
    align: "right",
    label: "Custo Total",
    field: "total_cost",
    type: "currency",
    sortable: true,
  },
];
